title: Jeremy Jang # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Master's Student in Computer Science at University of Southern California 
  <br><br>
  Website under construction
  <br><br>
  <a href="https://www.linkedin.com/in/jeremyjang/">LinkedIn</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-C4TPP6KSY3 # your Google Analytics tracking ID here
